### ISSUE TITLE
It seems, SOCKET should be a size_t ?

### ISSUE THREAD

**Issue by denizzzka** [etcimon/windows-headers#12]
Hi!

I found what D's druntime declares `SOCKET` as `size_t`

Also winsock2.h from Microsoft declares `SOCKET` as `UINT_PTR` (https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/um/WinSock2.h#L122)

`UINT_PTR` type is unsigned integer, whose length is dependent on processor word size (https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tsts/f959534d-51f2-4103-8fb5-812620efe49b)

**Comment by etcimon** [comment]
It is, that went under the radar because I didn't use this library for libasync, but rather for different features in desktop applications. Should be fixed
