### ISSUE TITLE
Erroneous comma in winhttp.d

### ISSUE THREAD

**Issue by KytoDragon** [etcimon/windows-headers#3]
Compiling this repository with a newer version of dmd allowed me to find this bug:
winhttp.d in line 657 says:
`	ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED = (WINHTTP_ERROR_BASE, + 44),`
I believe the comma between "WINHTTP_ERROR_BASE" and "+ 44" does not belong there.

The compiler now also complains about the implicit string concatenation at the start of aclui.d, errorrep.d and lmmsg.d. Please change that to use the string concatenation operator ~.

-Kyto

**Comment by etcimon** [comment]
Will do thanks =)

**Comment by dkorpel** [comment]
This is fixed now, can be closed
