### ISSUE TITLE
GetMonitorInfo - Same symbol differente mangle

### ISSUE THREAD

**Issue by dkorpel** [etcimon/windows-headers#5]
When compiling with LDC I got this error:
```
...\source\windows\winuser.d(4402,7): Error: Function type does not match previously declared function with the same mangled name: GetMonitorInfoW
...\source\windows\winuser.d(4402,7):        Previous IR type: i32 (i8*, %windows.winuser.MONITORINFO*)
...\source\windows\winuser.d(4402,7):        New IR type:      i32 (i8*, %windows.winuser.MONITORINFOEXW*)
```
The line in question is:
https://github.com/etcimon/windows-headers/blob/master/source/windows/winuser.d#L4399

Why are there two definitions for `GetMonitorInfoA` and `GetMonitorInfoW` there?

**Comment by etcimon** [comment]
This is likely because the mangling will be different, and windows offers the same function for 2 types of pointers to objects that will get populated accordingly

https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getmonitorinfoa

The question is, why does LDC believe a function with the same mangled name has a different structure.

**Comment by dkorpel** [comment]
> The question is, why does LDC believe a function with the same mangled name has a different structure.

Because under an `extern (Windows):` there are two definitions:
```D
	BOOL GetMonitorInfoA(HMONITOR, LPMONITORINFO);
	BOOL GetMonitorInfoA(HMONITOR, LPMONITORINFOEXA);
```

And those pointers are of two different structures:
```D
struct MONITORINFO {
	DWORD cbSize = this.sizeof;
	RECT rcMonitor;
	RECT rcWork;
	DWORD dwFlags;
}

struct MONITORINFOEXA {
	DWORD cbSize = MONITORINFOEXA.sizeof;
	RECT  rcMonitor;
	RECT  rcWork;
	DWORD dwFlags;
	CHAR[CCHDEVICENAME] szDevice;
}
```
LDC doesn't know that one is a subset of the other, so it complains it doesn't know which of these two structs GetMonitorInfoA accepts. Looking at the doc, it seems like only having the `LPMONITORINFO` should be fine, users of the EXT variant will just have to cast the pointer. Or is it currently possible to pass either pointer to the function with dmd?
