### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dkorpel** [etcimon/windows-headers#6]
Currently, the master branch contains some important deprecation fixes that packages with `"windows-headers": "~>1.0.1"` don't get. Can a 1.0.2 tag be created?

**Comment by etcimon** [comment]
Does v1.0.2 work? Which commit fixes the deprecation errors?

**Comment by dkorpel** [comment]
When using ggplotD (which uses cairoD which uses these headers) I needed to fix some deprecation errors. When I considered opening a PR, I already found one doing the same: 
https://github.com/etcimon/windows-headers/pull/4/files
And thought is was merged to master, just not in the newest version. But I see now that it was closed actually, maybe it can be re-opened.

**Comment by etcimon** [comment]
Most updates should now be in v1.0.3, let me know if it works

**Comment by dkorpel** [comment]
I've removed my old moficiations, upgraded to v1.0.3., rebuilt with dmd and ldc and it works now. Thanks for the swift response.
